# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mjosue <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/07/15 10:09:46 by mjosue            #+#    #+#              #
#    Updated: 2019/07/15 11:34:16 by mjosue           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME1 = ft_toupper.c ft_tolower.c ft_strstr.c ft_strrchr.c ft_strnstr.c ft_strncpy.c ft_strncmp.c ft_strncat.c ft_strlen.c ft_strlcat.c ft_strdup.c ft_strcpy.c ft_strcmp.c ft_strchr.c ft_strcat.c ft_memset.c ft_memmove.c ft_memcpy.c ft_memcmp.c ft_memchr.c ft_memccpy.c ft_isprint.c ft_isdigit.c ft_isascii.c ft_isalpha.c ft_isalnum.c ft_atoi.c ft_bzero.c ft_memalloc.c ft_memdel.c ft_strnew.c ft_strdel.c ft_strclr.c ft_striter.c ft_striteri.c ft_strmap.c ft_strmapi.c ft_strequ.c ft_strnequ.c ft_strsub.c ft_strjoin.c ft_strtrim.c ft_strsplit.c ft_itoa.c ft_putchar.c ft_putstr.c ft_putendl.c ft_putnbr.c ft_putchar_fd.c ft_putstr_fd.c ft_putendl_fd.c ft_putnbr_fd.c

NAME2 = ft_toupper.o ft_tolower.o ft_strstr.o ft_strrchr.o ft_strnstr.o ft_strncpy.o ft_strncmp.o ft_strncat.o ft_strlen.o ft_strlcat.o ft_strdup.o ft_strcpy.o ft_strcmp.o ft_strchr.o ft_strcat.o ft_memset.o ft_memmove.o ft_memcpy.o ft_memcmp.o ft_memchr.o ft_memccpy.o ft_isprint.o ft_isdigit.o ft_isascii.o ft_isalpha.o ft_isalnum.o ft_atoi.o ft_bzero.o ft_memalloc.o ft_memdel.o ft_strnew.o ft_strdel.o ft_strclr.o ft_striter.o ft_striteri.o ft_strmap.o ft_strmapi.o ft_strequ.o ft_strnequ.o ft_strsub.o ft_strjoin.o ft_strtrim.o ft_strsplit.o ft_itoa.o ft_putchar.o ft_putstr.o ft_putendl.o ft_putnbr.o ft_putchar_fd.o ft_putstr_fd.o ft_putendl_fd.o ft_putnbr_fd.o

NAME = libft.a

all: $(NAME)

$(NAME): 
	@gcc -Wall -Wextra -Werror -I ./ -c $(NAME1)
	@ar rc $(NAME) $(NAME2)
	
clean:
	@rm -f $(NAME2) 

fclean: clean
	@rm -f $(NAME)
		
re: fclean all



	

	

	
	

	

