# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mjosue <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/07/15 10:09:46 by mjosue            #+#    #+#              #
#    Updated: 2019/07/15 11:34:16 by mjosue           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #


all:
	@gcc -Wall -Wextra -Werror  main.c ft_putnbr.c -L. -lft

clean:
	rm -f *.o temp.txt

fclean: clean
	rm -f libft.a
	rm -f bsq
	
re: fclean all



	

	

	
	

	

