# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mjosue <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/07/15 10:09:46 by mjosue            #+#    #+#              #
#    Updated: 2019/07/15 11:34:16 by mjosue           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME1 =  main.c get_next_line.c




all: 
	@gcc -Wall -Wextra -Werror -I ./includes $(NAME1) -L. -lft 
	
clean:
	@rm -f $(NAME2) 

fclean: clean
	@rm -f a.out
		
re: fclean all



	

	

	
	

	

